export interface Sortie {
  id: string;
  nom: string;
  description: string;
  ageMin: number;
  ageMax: number;
  dureeEstimee: number;
  tarif?: string;
  adresse: string;
  informationsPratiques: string;
  objectifs?: string;
  categorie: string;
  emoji: string;
}

export const CATEGORIES_SORTIES = ['Parc', 'Musée', 'Atelier', 'Sport', 'Culture', 'Nature', 'Bibliothèque', 'Piscine', 'Marché', 'Jeux', 'Cinéma', 'Spectacle'] as const;

export const SORTIES: Sortie[] = [
  {
    id: 's-01',
    nom: 'Parc de la Tête d\'Or',
    description: 'Le plus grand parc urbain de Lyon avec un lac, un zoo gratuit et des espaces de jeux. Un incontournable pour les familles lyonnaises.',
    ageMin: 0,
    ageMax: 144,
    dureeEstimee: 180,
    tarif: 'Gratuit',
    adresse: 'Place du Général Leclerc, 69006 Lyon',
    informationsPratiques: 'Accès tram T1/T4 arrêt Tête d\'Or. Prévoir pique-nique, poussette bienvenue. Zoo ouvert 9h–17h30. Barques en location l\'été.',
    objectifs: 'Découverte de la faune et de la flore, plein air, motricité globale',
    categorie: 'Parc',
    emoji: '🌳',
  },
  {
    id: 's-02',
    nom: 'Parc des Hauteurs (Croix-Rousse)',
    description: 'Parc suspendu avec vue panoramique sur Lyon, jeux pour enfants et sentiers boisés. Idéal pour une balade en famille.',
    ageMin: 12,
    ageMax: 144,
    dureeEstimee: 90,
    tarif: 'Gratuit',
    adresse: 'Voie des Grandes Halles, 69004 Lyon',
    informationsPratiques: 'Accessible par les traboules de la Croix-Rousse ou en voiture. Terrain parfois pentu, bon pour les marcheurs. Aire de jeux sécurisée.',
    objectifs: 'Motricité globale, découverte de la ville',
    categorie: 'Parc',
    emoji: '🌿',
  },
  {
    id: 's-03',
    nom: 'Parc de Parilly',
    description: 'Grand espace naturel avec plaine de jeux, lac, mini-golf et circuit de ski nautique l\'été. Parfait pour une demi-journée sportive.',
    ageMin: 24,
    ageMax: 144,
    dureeEstimee: 120,
    tarif: 'Gratuit (activités payantes)',
    adresse: 'Boulevard Charles de Gaulle, 69500 Bron',
    informationsPratiques: 'Accès métro D, station Mermoz-Pinel puis marche 15 min. Parking gratuit. Restaurant sur place.',
    categorie: 'Parc',
    emoji: '⛵',
  },
  {
    id: 's-04',
    nom: 'Musée des Confluences',
    description: 'Musée de sciences naturelles et de sociétés aux collections impressionnantes. Architecture spectaculaire au confluent du Rhône et de la Saône.',
    ageMin: 36,
    ageMax: 144,
    dureeEstimee: 120,
    tarif: '9€/adulte, gratuit -18 ans',
    adresse: '86 Quai Perrache, 69002 Lyon',
    informationsPratiques: 'Mardi–dimanche 10h30–18h30, vendredi jusqu\'à 21h. Accès tram T1 arrêt Suchet. Poussettes acceptées. Espace enfants dédié.',
    objectifs: 'Éveil scientifique, découverte du monde, culture générale',
    categorie: 'Musée',
    emoji: '🔬',
  },
  {
    id: 's-05',
    nom: 'Musée Miniature et Cinéma',
    description: 'Un musée unique avec des décors miniatures époustouflants et des effets spéciaux de cinéma. Les enfants adorent chercher les détails cachés.',
    ageMin: 36,
    ageMax: 144,
    dureeEstimee: 90,
    tarif: '12€/adulte, 8€/enfant',
    adresse: '60 Rue Saint-Jean, 69005 Lyon',
    informationsPratiques: 'Lundi–vendredi 10h–18h, week-ends 9h30–19h. Vieux Lyon, accessible par le funiculaire. Réservation conseillée le week-end.',
    objectifs: 'Attention aux détails, curiosité, créativité',
    categorie: 'Musée',
    emoji: '🏛',
  },
  {
    id: 's-06',
    nom: 'Institut Lumière',
    description: 'Musée dédié aux frères Lumière, inventeurs du cinéma, dans leur villa d\'origine. Projections régulières de films muets avec accompagnement musical.',
    ageMin: 60,
    ageMax: 144,
    dureeEstimee: 90,
    tarif: '7€/adulte, 5€/enfant',
    adresse: '25 Rue du Premier Film, 69008 Lyon',
    informationsPratiques: 'Mardi–dimanche 10h–18h30. Accès tram T2 arrêt Institut Lumière. Programme des projections sur le site.',
    objectifs: 'Histoire des arts, culture cinématographique',
    categorie: 'Musée',
    emoji: '🎬',
  },
  {
    id: 's-07',
    nom: 'Musée des Beaux-Arts de Lyon',
    description: 'L\'un des plus grands musées de France, installé dans un ancien couvent. Collections d\'antiquités, peintures et sculptures.',
    ageMin: 48,
    ageMax: 144,
    dureeEstimee: 120,
    tarif: '8€/adulte, gratuit -18 ans',
    adresse: '20 Place des Terreaux, 69001 Lyon',
    informationsPratiques: 'Lundi, mercredi–dimanche 10h–18h. Accès métro A arrêt Hôtel de Ville. Visites guidées famille disponibles sur réservation.',
    objectifs: 'Sensibilité artistique, histoire de l\'art',
    categorie: 'Musée',
    emoji: '🎨',
  },
  {
    id: 's-08',
    nom: 'Atelier céramique enfants — Lyon Poterie',
    description: 'Cours de poterie adaptés aux enfants à partir de 4 ans. Modelage libre ou sur thème, cuisson et émaillage inclus.',
    ageMin: 48,
    ageMax: 144,
    dureeEstimee: 90,
    tarif: '18€/enfant',
    adresse: '12 Rue de la Martinière, 69001 Lyon',
    informationsPratiques: 'Sur réservation uniquement. Vêtements qui ne craignent pas les taches. La pièce est prête à récupérer 3 semaines après.',
    objectifs: 'Motricité fine, créativité, patience, vie pratique',
    categorie: 'Atelier',
    emoji: '🏺',
  },
  {
    id: 's-09',
    nom: 'Atelier cuisine enfants — L\'Atelier des Sens',
    description: 'Atelier culinaire spécialement conçu pour les enfants. Recettes simples et ludiques, apprentissage des techniques de base.',
    ageMin: 36,
    ageMax: 120,
    dureeEstimee: 120,
    tarif: '25€/enfant',
    adresse: '28 Rue du Chariot d\'Or, 69004 Lyon',
    informationsPratiques: 'Séances week-end et mercredis. Réservation en ligne obligatoire. Les enfants repartent avec leurs réalisations.',
    objectifs: 'Vie pratique, autonomie, sens du goût, mathématiques (mesures)',
    categorie: 'Atelier',
    emoji: '👨‍🍳',
  },
  {
    id: 's-10',
    nom: 'Atelier peinture — Les Petits Artistes',
    description: 'Atelier créatif avec différentes techniques : aquarelle, acrylique, collage. Un espace bienveillant pour les jeunes artistes.',
    ageMin: 36,
    ageMax: 120,
    dureeEstimee: 90,
    tarif: '15€/enfant',
    adresse: '45 Grande Rue de la Guillotière, 69007 Lyon',
    informationsPratiques: 'Mercredis et samedis matins. Tous les matériaux fournis. Vêtements à laisser ou tablier fourni.',
    objectifs: 'Créativité, expression artistique, motricité fine',
    categorie: 'Atelier',
    emoji: '🖌',
  },
  {
    id: 's-11',
    nom: 'Piscine de Gerland',
    description: 'Grande piscine avec bassins couverts et pataugeoire pour les tout-petits. Idéale pour les premières expériences aquatiques.',
    ageMin: 6,
    ageMax: 144,
    dureeEstimee: 90,
    tarif: '4€/adulte, 2,50€/enfant',
    adresse: '1 Avenue Debourg, 69007 Lyon',
    informationsPratiques: 'Horaires variables, consulter le site. Fermeture le lundi matin. Pataugeoire réservée aux enfants accompagnés.',
    objectifs: 'Motricité aquatique, confiance en soi',
    categorie: 'Piscine',
    emoji: '🏊',
  },
  {
    id: 's-12',
    nom: 'Piscine Tony Bertrand',
    description: 'Piscine en plein air ouverte l\'été avec vue sur le Rhône. Un moment de détente pour toute la famille.',
    ageMin: 12,
    ageMax: 144,
    dureeEstimee: 120,
    tarif: '4,50€/adulte, 3€/enfant',
    adresse: '4 Quai Claude Bernard, 69007 Lyon',
    informationsPratiques: 'Ouverte juin–août selon météo. Accessible à pied depuis les berges du Rhône. Snack sur place.',
    categorie: 'Piscine',
    emoji: '🌊',
  },
  {
    id: 's-13',
    nom: 'Bibliothèque du 1er — Salle jeunesse',
    description: 'Espace jeunesse avec albums illustrés, contes et coins lecture confortables. Des animations gratuites sont proposées régulièrement.',
    ageMin: 0,
    ageMax: 96,
    dureeEstimee: 60,
    tarif: 'Gratuit',
    adresse: '8 Place Saint-Jean de Dieu, 69001 Lyon',
    informationsPratiques: 'Mardi–samedi selon horaires. Inscription gratuite avec justificatif de domicile. Heure du conte le mercredi matin.',
    objectifs: 'Langage, prélecture, imaginaire',
    categorie: 'Bibliothèque',
    emoji: '📚',
  },
  {
    id: 's-14',
    nom: 'Bibliothèque Part-Dieu — Espace enfants',
    description: 'La plus grande bibliothèque de Lyon avec un espace enfants lumineux et fourni. Bandes dessinées, livres documentaires et romans.',
    ageMin: 0,
    ageMax: 144,
    dureeEstimee: 90,
    tarif: 'Gratuit',
    adresse: '30 Boulevard Vivier Merle, 69003 Lyon',
    informationsPratiques: 'Lundi 13h–19h, mardi–vendredi 10h–19h, samedi 10h–18h. Accès métro B et D arrêt Part-Dieu.',
    objectifs: 'Langage, autonomie, culture générale',
    categorie: 'Bibliothèque',
    emoji: '📖',
  },
  {
    id: 's-15',
    nom: 'Colline de Fourvière',
    description: 'La colline qui prie, avec sa basilique emblématique, ses jardins et son théâtre gallo-romain. Magnifique vue sur la ville.',
    ageMin: 24,
    ageMax: 144,
    dureeEstimee: 120,
    tarif: 'Gratuit',
    adresse: '8 Place de Fourvière, 69005 Lyon',
    informationsPratiques: 'Accès par funiculaire depuis Vieux-Lyon (1,90€). Musée gallo-romain adjacent. Pique-nique dans les jardins possible.',
    objectifs: 'Histoire, géographie locale, nature',
    categorie: 'Nature',
    emoji: '⛪',
  },
  {
    id: 's-16',
    nom: 'Berges du Rhône',
    description: 'Promenade le long du Rhône, avec des espaces de jeux, des aires de pique-nique et une belle végétation. Parfait pour les vélos et trottinettes.',
    ageMin: 0,
    ageMax: 144,
    dureeEstimee: 90,
    tarif: 'Gratuit',
    adresse: 'Quai du Général Sarrail, 69006 Lyon',
    informationsPratiques: 'Accessible à pied ou en vélo. Buvettes et restaurants en saison. Piste cyclable sur toute la longueur.',
    objectifs: 'Motricité globale, plein air',
    categorie: 'Nature',
    emoji: '🚴',
  },
  {
    id: 's-17',
    nom: 'Jardin Rosa Mir',
    description: 'Jardin secret et poétique créé par un artiste autodidacte, niché dans la Croix-Rousse. Une découverte hors des sentiers battus.',
    ageMin: 24,
    ageMax: 144,
    dureeEstimee: 45,
    tarif: 'Gratuit',
    adresse: '87 Grande Rue de la Croix-Rousse, 69004 Lyon',
    informationsPratiques: 'Ouvert les week-ends et certains jours en semaine selon bénévoles. Accès métro C arrêt Croix-Rousse.',
    objectifs: 'Curiosité, imaginaire, découverte artistique',
    categorie: 'Nature',
    emoji: '🌸',
  },
  {
    id: 's-18',
    nom: 'Stade de Vitesse Olympique',
    description: 'Initiation à l\'athlétisme pour enfants dans un cadre sportif professionnel. Séances d\'éveil sportif pour les plus jeunes.',
    ageMin: 36,
    ageMax: 120,
    dureeEstimee: 90,
    tarif: '5€/séance',
    adresse: '351 Avenue Jean Jaurès, 69007 Lyon',
    informationsPratiques: 'Séances le mercredi après-midi. Tenue sport obligatoire. Accès tram T2 arrêt Stade de Gerland.',
    objectifs: 'Motricité globale, esprit sportif, coordination',
    categorie: 'Sport',
    emoji: '🏃',
  },
  {
    id: 's-19',
    nom: 'Lyon Science — Planétarium',
    description: 'Séances de planétarium pour découvrir l\'astronomie de manière immersive. Des projections adaptées aux enfants dès 5 ans.',
    ageMin: 60,
    ageMax: 144,
    dureeEstimee: 60,
    tarif: '6€/personne',
    adresse: '1 Rue Anselme Coste, 69100 Villeurbanne',
    informationsPratiques: 'Séances sur réservation. Programmation variée. Accès tram T1 ou T3. Durée environ 50 min par séance.',
    objectifs: 'Éveil scientifique, curiosité, cosmologie',
    categorie: 'Culture',
    emoji: '🔭',
  },
  {
    id: 's-20',
    nom: 'Théâtre de la Maison de la Danse',
    description: 'Spectacles de danse contemporaine avec programmation jeune public. Une belle initiation aux arts du corps.',
    ageMin: 36,
    ageMax: 144,
    dureeEstimee: 75,
    tarif: '8€/enfant, 12€/adulte',
    adresse: '8 Avenue Jean Mermoz, 69008 Lyon',
    informationsPratiques: 'Programme en ligne sur le site. Spectacles jeune public souvent le mercredi ou week-end matin. Réservation conseillée.',
    objectifs: 'Sensibilité artistique, écoute, expression corporelle',
    categorie: 'Culture',
    emoji: '💃',
  },
  {
    id: 's-21',
    nom: 'Opéra de Lyon — Visites famille',
    description: 'Visites guidées de l\'Opéra pour découvrir les coulisses : loges, machinerie scénique, salles de répétition. Magique pour les enfants curieux.',
    ageMin: 60,
    ageMax: 144,
    dureeEstimee: 90,
    tarif: '5€/personne',
    adresse: '1 Place de la Comédie, 69001 Lyon',
    informationsPratiques: 'Visites les samedis sur réservation. Programme aussi des concerts jeune public accessibles dès 3 ans.',
    objectifs: 'Culture musicale, découverte des arts de la scène',
    categorie: 'Culture',
    emoji: '🎭',
  },
  {
    id: 's-22',
    nom: 'Espace Sportif Charpennes',
    description: 'Espace multisport avec escalade, badminton et cours collectifs pour enfants. Une bonne alternative aux activités habituelles.',
    ageMin: 48,
    ageMax: 144,
    dureeEstimee: 90,
    tarif: '6€/enfant',
    adresse: '74 Boulevard du 11 Novembre 1918, 69100 Villeurbanne',
    informationsPratiques: 'Ouvert tous les jours. Cours enfants le mercredi et samedi. Tenue sport et chaussons d\'escalade (location possible).',
    objectifs: 'Motricité globale, dépassement de soi, socialisation',
    categorie: 'Sport',
    emoji: '🧗',
  },

  // ── Décines et alentours ──────────────────────────────────────────────────

  {
    id: 's-23',
    nom: 'Marché de Décines (près de l\'église)',
    description: 'Le marché du centre-ville de Décines, animé et convivial, installé près de l\'église Saint-Jean-Baptiste. Fruits, légumes, fromages, fleurs… une belle façon de découvrir les saisons avec les enfants.',
    ageMin: 0,
    ageMax: 144,
    dureeEstimee: 60,
    tarif: 'Gratuit',
    adresse: 'Place de la Nation, 69150 Décines-Charpieu',
    informationsPratiques: 'Marché le jeudi matin et le dimanche matin. Prévoir un cabas. Parking à proximité. Idéal pour faire les courses ensemble et nommer les légumes.',
    objectifs: 'Vie pratique, langage, découverte des aliments et des saisons',
    categorie: 'Marché',
    emoji: '🛒',
  },
  {
    id: 's-24',
    nom: 'Marché du Pré de Justin',
    description: 'Petit marché de quartier au Pré de Justin, à taille humaine et très familial. Une atmosphère de village où les commerçants prennent le temps d\'échanger.',
    ageMin: 0,
    ageMax: 144,
    dureeEstimee: 45,
    tarif: 'Gratuit',
    adresse: 'Quartier Pré de Justin, 69150 Décines-Charpieu',
    informationsPratiques: 'Marché le matin en semaine. Facile en poussette. Bon endroit pour initier les enfants aux achats et à la monnaie.',
    objectifs: 'Vie pratique, autonomie, langage',
    categorie: 'Marché',
    emoji: '🥦',
  },
  {
    id: 's-25',
    nom: 'Marché du Pré de Charly',
    description: 'Marché de proximité dans le quartier Pré de Charly. Producteurs locaux et artisans, ambiance chaleureuse et accessible à pied pour les habitants du secteur.',
    ageMin: 0,
    ageMax: 144,
    dureeEstimee: 45,
    tarif: 'Gratuit',
    adresse: 'Quartier Pré de Charly, 69150 Décines-Charpieu',
    informationsPratiques: 'Vérifier les jours et horaires auprès de la mairie de Décines. Prévoir un sac réutilisable. Parfait pour une sortie matinale courte.',
    objectifs: 'Vie pratique, découverte des producteurs locaux',
    categorie: 'Marché',
    emoji: '🍎',
  },
  {
    id: 's-26',
    nom: 'Médiathèque de Décines',
    description: 'La médiathèque de Décines-Charpieu propose un bel espace jeunesse avec albums, contes, BD et documentaires. Des animations régulières pour les tout-petits et les enfants.',
    ageMin: 0,
    ageMax: 120,
    dureeEstimee: 75,
    tarif: 'Gratuit',
    adresse: '3 Avenue du Général de Gaulle, 69150 Décines-Charpieu',
    informationsPratiques: 'Horaires variables selon les jours, fermée le lundi. Inscription gratuite avec justificatif de domicile. Heure du conte et ateliers régulièrement proposés — programme sur le site de la ville.',
    objectifs: 'Langage, prélecture, imaginaire, amour des livres',
    categorie: 'Bibliothèque',
    emoji: '📚',
  },
  {
    id: 's-27',
    nom: 'Ludothèque de Décines',
    description: 'La ludothèque met à disposition des jeux pour tous les âges dans un espace convivial et encadré. Les enfants explorent librement, échangent et jouent ensemble.',
    ageMin: 12,
    ageMax: 120,
    dureeEstimee: 90,
    tarif: 'Adhésion annuelle modique',
    adresse: 'Décines-Charpieu (se renseigner auprès de la mairie)',
    informationsPratiques: 'Sur adhésion. Certains jeux peuvent être empruntés à la maison. Séances libres et ateliers animés. Idéal pour les jours de pluie.',
    objectifs: 'Construction et logique, socialisation, créativité, langage',
    categorie: 'Jeux',
    emoji: '🎲',
  },
  {
    id: 's-28',
    nom: 'Mini World Lyon',
    description: 'Un univers miniature fascinant avec des maquettes détaillées de villes, aéroports, gares et paysages animés. Les enfants cherchent les petits personnages et les scènes cachées pendant des heures.',
    ageMin: 24,
    ageMax: 144,
    dureeEstimee: 120,
    tarif: '14€/adulte, 10€/enfant, gratuit -3 ans',
    adresse: 'À proximité du Groupama Stadium, 69150 Décines-Charpieu',
    informationsPratiques: 'Ouvert tous les jours — horaires sur miniworld.fr. À 10 min à pied du stade. Accessible en tramway T3. Boutique sur place. Prévoir au moins 1h30.',
    objectifs: 'Attention aux détails, curiosité, géographie, imaginaire',
    categorie: 'Musée',
    emoji: '🏙',
  },
  {
    id: 's-29',
    nom: 'Mini-séance Pathé Gômont',
    description: 'Les mini-séances sont des projections courtes spécialement conçues pour les bébés et les tout-petits (0–3 ans). Lumière tamisée, son adouci, durée courte. Une première expérience du cinéma en douceur.',
    ageMin: 0,
    ageMax: 48,
    dureeEstimee: 45,
    tarif: 'Environ 5€/place',
    adresse: '36 Cours d\'Herbouville, 69004 Lyon',
    informationsPratiques: 'Séances le mardi ou mercredi matin selon programme. Réservation conseillée sur le site Pathé. Allaitement et changes bienvenus. Les accompagnateurs adultes ont aussi leur billet.',
    objectifs: 'Éveil sensoriel, attention, découverte du son et de l\'image',
    categorie: 'Cinéma',
    emoji: '🎞',
  },
  {
    id: 's-30',
    nom: 'Sortie vélo — Voie verte vers Lyon',
    description: 'Depuis Décines, la voie verte longeant le Rhône permet une belle balade à vélo en famille jusqu\'aux berges de Lyon. Piste sécurisée, sans voiture, avec des aires de repos.',
    ageMin: 36,
    ageMax: 144,
    dureeEstimee: 120,
    tarif: 'Gratuit',
    adresse: 'Départ : berges du Rhône, Décines-Charpieu',
    informationsPratiques: 'Idéal avec siège bébé ou remorque pour les plus petits. Prévoir eau et goûter. Arrivée possible aux Berges du Rhône de Lyon (quai). Revenir en tram T3 avec les vélos si fatigue.',
    objectifs: 'Motricité globale, plein air, autonomie, découverte du paysage',
    categorie: 'Sport',
    emoji: '🚴',
  },
  {
    id: 's-31',
    nom: 'Kids World',
    description: 'Grande structure de jeux intérieurs pour les enfants avec toboggans, trampolines, espaces de jeux créatifs et coin café pour les parents. Idéal les jours de pluie.',
    ageMin: 12,
    ageMax: 120,
    dureeEstimee: 120,
    tarif: 'Environ 8–10€/enfant, gratuit accompagnateurs',
    adresse: 'Région lyonnaise — vérifier l\'adresse exacte sur leur site',
    informationsPratiques: 'Ouvert en semaine et le week-end. Chaussettes obligatoires. Espace séparé pour les moins de 3 ans. Réservation conseillée le week-end.',
    objectifs: 'Motricité globale, socialisation, autonomie',
    categorie: 'Jeux',
    emoji: '🎠',
  },
  {
    id: 's-32',
    nom: 'La Baie des Pirates',
    description: 'Espace de jeux intérieurs sur le thème des pirates avec structure à grimper, toboggan géant, coins jeux et espace pour les bébés. Les enfants adorent l\'univers aventurier.',
    ageMin: 6,
    ageMax: 108,
    dureeEstimee: 120,
    tarif: 'Environ 9€/enfant, gratuit accompagnateurs',
    adresse: 'Région lyonnaise — vérifier l\'adresse exacte sur leur site',
    informationsPratiques: 'Ouvert tous les jours. Chaussettes obligatoires. Snack et boissons disponibles sur place. Anniversaires possibles sur réservation.',
    objectifs: 'Motricité globale, imaginaire, socialisation',
    categorie: 'Jeux',
    emoji: '🏴‍☠️',
  },
  {
    id: 's-33',
    nom: 'La Péniche Spectacle sur le Rhône',
    description: 'Une péniche amarrée sur le Rhône transformée en salle de spectacle intimiste. Concerts, contes, théâtre jeune public... une expérience unique sur l\'eau pour toute la famille.',
    ageMin: 24,
    ageMax: 144,
    dureeEstimee: 60,
    tarif: 'Environ 8–12€/personne',
    adresse: 'Berges du Rhône, Lyon (programme sur place)',
    informationsPratiques: 'Programme variable — consulter les affiches et réseaux sociaux. Arrivée 15 min avant. Capacité limitée, réservation conseillée. Accessible en tram ou vélo.',
    objectifs: 'Sensibilité artistique, écoute, découverte culturelle',
    categorie: 'Spectacle',
    emoji: '⛵',
  },
  {
    id: 's-34',
    nom: 'Nuits de Fourvière – Séances jeune public',
    description: 'Le festival des Nuits de Fourvière propose chaque été des spectacles jeune public dans le magnifique cadre du théâtre gallo-romain. Cirque, marionnettes, contes et danse sous les étoiles.',
    ageMin: 36,
    ageMax: 144,
    dureeEstimee: 75,
    tarif: 'À partir de 8€/enfant',
    adresse: 'Théâtre antique de Fourvière, 6 Rue de l\'Antiquaille, 69005 Lyon',
    informationsPratiques: 'Juin–juillet uniquement. Réservation en ligne obligatoire sur nuitsdefourviere.com. Prévoir une couverture le soir. Accès funiculaire.',
    objectifs: 'Sensibilité artistique, culture, découverte des arts vivants',
    categorie: 'Spectacle',
    emoji: '🎪',
  },
  {
    id: 's-35',
    nom: 'Théâtre de Guignol de Lyon',
    description: 'Le célèbre Guignol lyonnais, né à Lyon au XIXe siècle. Des spectacles de marionnettes drôles et vivants, une tradition familiale incontournable de la ville.',
    ageMin: 24,
    ageMax: 96,
    dureeEstimee: 45,
    tarif: '5–7€/personne',
    adresse: 'Jardin du Parc de la Tête d\'Or ou théâtres partenaires, Lyon',
    informationsPratiques: 'Séances les mercredis, samedis et dimanches. Arriver 10 min avant. Les enfants adorent répondre à Guignol. Programme sur guignol-lyon.com.',
    objectifs: 'Langage, imaginaire, humour, héritage culturel lyonnais',
    categorie: 'Spectacle',
    emoji: '🎭',
  },
  {
    id: 's-36',
    nom: 'Cirque Électrique – Séances enfants',
    description: 'Spectacles de cirque contemporain accessibles aux enfants dès 2 ans. Acrobaties, jonglage, clownerie dans une ambiance chaleureuse et bienveillante.',
    ageMin: 24,
    ageMax: 120,
    dureeEstimee: 60,
    tarif: '7–10€/personne',
    adresse: 'Venues variables à Lyon et agglomération',
    informationsPratiques: 'Programme sur les sites des théâtres lyonnais (TNP, Théâtre du Vieux-Lyon, etc.). Séances spéciales "bébés spectateurs" pour les moins de 3 ans dans certains lieux.',
    objectifs: 'Sensibilité artistique, éveil corporel, émerveillement',
    categorie: 'Spectacle',
    emoji: '🤹',
  },
  {
    id: 's-37',
    nom: 'Théâtre Rikiki',
    description: 'Théâtre dédié au jeune public à Lyon, connu pour ses spectacles de marionnettes, de contes et de théâtre d\'objets. Une programmation entièrement pensée pour les tout-petits et les enfants jusqu\'à 10 ans, dans une salle à taille humaine et chaleureuse.',
    ageMin: 18,
    ageMax: 120,
    dureeEstimee: 50,
    tarif: '7–9€/personne',
    adresse: 'Lyon (consulter le site pour l\'adresse exacte et la programmation en cours)',
    informationsPratiques: 'Séances les mercredis, samedis et dimanches. Réservation conseillée car jauges limitées. Idéal pour une première expérience au théâtre. Certains spectacles sont accessibles dès 18 mois. Programme régulièrement renouvelé.',
    objectifs: 'Sensibilité artistique, imaginaire, langage, écoute et concentration',
    categorie: 'Spectacle',
    emoji: '🎪',
  },
  {
    id: 's-38',
    nom: 'Théâtre de l\'Île Ô',
    description: 'Espace culturel et théâtral proposant une programmation jeune public variée : théâtre d\'objets, marionnettes, contes musicaux et spectacles participatifs. Un lieu accueillant où les enfants sont au cœur de l\'expérience.',
    ageMin: 24,
    ageMax: 144,
    dureeEstimee: 55,
    tarif: '8–10€/personne',
    adresse: 'Lyon et agglomération (programme sur place ou site dédié)',
    informationsPratiques: 'Programmation jeune public les week-ends et mercredis après-midi. Certains spectacles proposent une participation active des enfants. Vérifier les tranches d\'âge selon les spectacles. Réservation recommandée.',
    objectifs: 'Créativité, expression, écoute, découverte des arts vivants',
    categorie: 'Spectacle',
    emoji: '🏝',
  },
  {
    id: 's-39',
    nom: 'Aquarium de Lyon',
    description: 'L\'aquarium de Lyon accueille des centaines d\'espèces marines et d\'eau douce dans des bassins immersifs. Piranhas, requins, méduses, tortues et poissons tropicaux fascinent petits et grands. Un voyage sous-marin au cœur de la ville.',
    ageMin: 12,
    ageMax: 144,
    dureeEstimee: 90,
    tarif: 'Environ 12€/adulte, 8€/enfant, gratuit -3 ans',
    adresse: 'Lyon (vérifier l\'adresse exacte sur aquariumdelyon.fr)',
    informationsPratiques: 'Ouvert tous les jours. Prévoir 1h30 minimum. Boutique sur place. Idéal pour parler des écosystèmes et de la biodiversité aquatique. Éviter les week-ends très chargés — mieux en semaine hors vacances.',
    objectifs: 'Éveil scientifique, découverte de la biodiversité, curiosité, biologie marine',
    categorie: 'Musée',
    emoji: '🐠',
  },
];
