/**
 * FAMILY OS — Seed Produits
 * src/core/db/seedProduits.ts
 *
 * ~120 produits courants pré-chargés au premier lancement.
 * Appelé depuis seedDatabase() dans seed.ts après seedCategoriesProduits().
 *
 * Les IDs de catégories sont récupérés dynamiquement par nom
 * car seedCategoriesProduits() génère des UUIDs aléatoires.
 */

import { db } from '@core/db/database';
import { normaliserNom } from '@core/produits/ProduitService';
import { newEntity } from '@core/db/helpers';
import type { Produit } from '@shared/types';

interface ProduitSeed {
  nom: string;
  unite?: string;
  marque?: string;
}

const PRODUITS_PAR_CATEGORIE: Record<string, ProduitSeed[]> = {
  Fruits: [
    { nom: 'Bananes', unite: 'kg' },
    { nom: 'Pommes', unite: 'kg' },
    { nom: 'Oranges', unite: 'kg' },
    { nom: 'Fraises', unite: 'barquette' },
    { nom: 'Raisins', unite: 'kg' },
    { nom: 'Poires', unite: 'kg' },
    { nom: 'Abricots', unite: 'kg' },
    { nom: 'Pêches', unite: 'kg' },
    { nom: 'Kiwis', unite: 'pièce(s)' },
    { nom: 'Citrons', unite: 'pièce(s)' },
    { nom: 'Pastèque', unite: 'pièce(s)' },
    { nom: 'Melon', unite: 'pièce(s)' },
  ],
  Légumes: [
    { nom: 'Carottes', unite: 'kg' },
    { nom: 'Pommes de terre', unite: 'kg' },
    { nom: 'Tomates', unite: 'kg' },
    { nom: 'Courgettes', unite: 'pièce(s)' },
    { nom: 'Poivrons', unite: 'pièce(s)' },
    { nom: 'Oignons', unite: 'kg' },
    { nom: 'Ail', unite: 'tête(s)' },
    { nom: 'Salade verte', unite: 'pièce(s)' },
    { nom: 'Épinards', unite: 'sachet(s)' },
    { nom: 'Brocolis', unite: 'pièce(s)' },
    { nom: 'Champignons', unite: 'barquette' },
    { nom: 'Concombre', unite: 'pièce(s)' },
    { nom: 'Poireaux', unite: 'pièce(s)' },
    { nom: 'Aubergine', unite: 'pièce(s)' },
  ],
  'Produits frais': [
    { nom: 'Lait demi-écrémé', unite: 'L' },
    { nom: 'Lait entier', unite: 'L' },
    { nom: 'Beurre', unite: 'g' },
    { nom: 'Crème fraîche', unite: 'ml' },
    { nom: 'Yaourt nature', unite: 'pièce(s)' },
    { nom: 'Yaourt aux fruits', unite: 'pièce(s)' },
    { nom: 'Œufs', unite: 'pièce(s)' },
    { nom: 'Fromage râpé', unite: 'g' },
    { nom: 'Emmental', unite: 'g' },
    { nom: 'Camembert', unite: 'pièce(s)' },
    { nom: 'Poulet entier', unite: 'kg' },
    { nom: 'Escalopes de poulet', unite: 'kg' },
    { nom: 'Steak haché', unite: 'g' },
    { nom: 'Poisson blanc', unite: 'g' },
    { nom: 'Saumon', unite: 'g' },
    { nom: 'Jus d\'orange frais', unite: 'L' },
  ],
  Épicerie: [
    { nom: 'Riz basmati', unite: 'kg' },
    { nom: 'Pâtes', unite: 'kg' },
    { nom: 'Spaghetti', unite: 'kg' },
    { nom: 'Farine de blé', unite: 'kg' },
    { nom: 'Sucre en poudre', unite: 'kg' },
    { nom: 'Sucre glace', unite: 'kg' },
    { nom: 'Sel', unite: 'g' },
    { nom: 'Poivre noir', unite: 'g' },
    { nom: 'Huile d\'olive', unite: 'ml' },
    { nom: 'Huile de tournesol', unite: 'ml' },
    { nom: 'Vinaigre', unite: 'ml' },
    { nom: 'Sauce tomate', unite: 'boîte(s)' },
    { nom: 'Concentré de tomates', unite: 'boîte(s)' },
    { nom: 'Pois chiches', unite: 'boîte(s)' },
    { nom: 'Lentilles', unite: 'g' },
    { nom: 'Thon en boîte', unite: 'boîte(s)' },
    { nom: 'Levure chimique', unite: 'sachet(s)' },
    { nom: 'Levure de boulanger', unite: 'sachet(s)' },
    { nom: 'Chocolat noir', unite: 'g' },
    { nom: 'Miel', unite: 'g' },
    { nom: 'Confiture', unite: 'pot(s)' },
    { nom: 'Semoule', unite: 'g' },
    { nom: 'Couscous', unite: 'g' },
  ],
  Surgelés: [
    { nom: 'Petits pois surgelés', unite: 'kg' },
    { nom: 'Épinards surgelés', unite: 'kg' },
    { nom: 'Frites surgelées', unite: 'kg' },
    { nom: 'Pizza surgelée', unite: 'pièce(s)' },
    { nom: 'Poisson pané surgelé', unite: 'pièce(s)' },
    { nom: 'Mélange légumes surgelés', unite: 'kg' },
    { nom: 'Glace vanille', unite: 'L' },
  ],
  Boissons: [
    { nom: 'Eau minérale', unite: 'L' },
    { nom: 'Eau gazeuse', unite: 'L' },
    { nom: 'Eau de coco', unite: 'ml' },
    { nom: 'Eau pétillante', unite: 'L' },
    { nom: 'Jus de pomme', unite: 'L' },
    { nom: 'Jus de raisin', unite: 'L' },
    { nom: 'Jus d\'orange', unite: 'L' },
    { nom: 'Sirop de menthe', unite: 'ml' },
    { nom: 'Café moulu', unite: 'g' },
    { nom: 'Thé', unite: 'boîte(s)' },
    { nom: 'Lait de croissance', unite: 'L' },
  ],
  Bébé: [
    { nom: 'Couches taille 3', unite: 'paquet(s)' },
    { nom: 'Couches taille 4', unite: 'paquet(s)' },
    { nom: 'Couches taille 5', unite: 'paquet(s)' },
    { nom: 'Lingettes bébé', unite: 'paquet(s)' },
    { nom: 'Crème change bébé', unite: 'tube(s)' },
    { nom: 'Shampoing bébé', unite: 'flacon(s)' },
    { nom: 'Petits pots légumes', unite: 'pièce(s)' },
    { nom: 'Petits pots fruits', unite: 'pièce(s)' },
    { nom: 'Céréales bébé', unite: 'boîte(s)' },
  ],
  Hygiène: [
    { nom: 'Dentifrice', unite: 'tube(s)' },
    { nom: 'Brosse à dents', unite: 'pièce(s)' },
    { nom: 'Savon liquide', unite: 'flacon(s)' },
    { nom: 'Savon solide', unite: 'pièce(s)' },
    { nom: 'Shampoing', unite: 'flacon(s)' },
    { nom: 'Après-shampoing', unite: 'flacon(s)' },
    { nom: 'Gel douche', unite: 'flacon(s)' },
    { nom: 'Déodorant', unite: 'pièce(s)' },
    { nom: 'Papier toilette', unite: 'paquet(s)' },
    { nom: 'Mouchoirs', unite: 'boîte(s)' },
    { nom: 'Coton-tiges', unite: 'boîte(s)' },
    { nom: 'Serviettes hygiéniques', unite: 'paquet(s)' },
  ],
  Entretien: [
    { nom: 'Lessive liquide', unite: 'L' },
    { nom: 'Lessive capsules', unite: 'paquet(s)' },
    { nom: 'Adoucissant', unite: 'L' },
    { nom: 'Liquide vaisselle', unite: 'flacon(s)' },
    { nom: 'Pastilles lave-vaisselle', unite: 'paquet(s)' },
    { nom: 'Produit nettoyant WC', unite: 'flacon(s)' },
    { nom: 'Produit nettoyant salle de bain', unite: 'flacon(s)' },
    { nom: 'Spray multi-surfaces', unite: 'flacon(s)' },
    { nom: 'Sacs poubelle', unite: 'rouleau(x)' },
    { nom: 'Éponges', unite: 'paquet(s)' },
    { nom: 'Papier essuie-tout', unite: 'rouleau(x)' },
  ],

  // ─── Huiles, vinaigres & corps gras ─────────────────────────────────────────
  // Note : 'Huile d\'olive' et 'Huile de tournesol' existent déjà → ignorés
  'Épicerie salée': [
    // Huiles
    { nom: 'Huile d\'olive vierge extra', unite: 'ml' },
    { nom: 'Huile de colza', unite: 'ml' },
    { nom: 'Huile d\'arachide', unite: 'ml' },
    { nom: 'Huile de sésame', unite: 'ml' },
    { nom: 'Huile de sésame grillé', unite: 'ml' },
    { nom: 'Huile de coco', unite: 'ml' },
    { nom: 'Huile d\'avocat', unite: 'ml' },
    { nom: 'Huile de pépins de raisin', unite: 'ml' },
    { nom: 'Huile de maïs', unite: 'ml' },
    { nom: 'Huile de soja', unite: 'ml' },
    { nom: 'Huile de noix', unite: 'ml' },
    { nom: 'Huile de noisette', unite: 'ml' },
    { nom: 'Huile d\'amande', unite: 'ml' },
    { nom: 'Huile de lin', unite: 'ml' },
    { nom: 'Huile de cameline', unite: 'ml' },
    { nom: 'Huile de riz', unite: 'ml' },
    { nom: 'Huile de palme', unite: 'ml' },
    { nom: 'Huile pimentée', unite: 'ml' },
    { nom: 'Huile parfumée à la truffe', unite: 'ml' },
    // Vinaigres — 'Vinaigre' générique existe déjà → ignoré
    { nom: 'Vinaigre blanc', unite: 'ml' },
    { nom: 'Vinaigre d\'alcool', unite: 'ml' },
    { nom: 'Vinaigre de vin rouge', unite: 'ml' },
    { nom: 'Vinaigre de vin blanc', unite: 'ml' },
    { nom: 'Vinaigre de cidre', unite: 'ml' },
    { nom: 'Vinaigre balsamique', unite: 'ml' },
    { nom: 'Vinaigre balsamique blanc', unite: 'ml' },
    { nom: 'Vinaigre de xérès', unite: 'ml' },
    { nom: 'Vinaigre de riz', unite: 'ml' },
    { nom: 'Vinaigre noir chinois', unite: 'ml' },
    { nom: 'Vinaigre de malt', unite: 'ml' },
    { nom: 'Vinaigre de champagne', unite: 'ml' },
    { nom: 'Vinaigre de framboise', unite: 'ml' },
    { nom: 'Vinaigre de noix', unite: 'ml' },
    // Jus acides
    { nom: 'Jus de citron', unite: 'ml' },
    { nom: 'Jus de citron vert', unite: 'ml' },
    { nom: 'Verjus', unite: 'ml' },
    // Corps gras animaux & végétaux
    { nom: 'Saindoux', unite: 'g' },
    { nom: 'Graisse de canard', unite: 'g' },
    { nom: 'Graisse d\'oie', unite: 'g' },
    { nom: 'Graisse de bœuf', unite: 'g' },
    { nom: 'Suif', unite: 'g' },
    { nom: 'Margarine', unite: 'g' },
    { nom: 'Shortening', unite: 'g' },
    { nom: 'Spray de cuisson', unite: 'flacon(s)' },
    { nom: 'Crème de coco', unite: 'ml' },
    { nom: 'Lait de coco', unite: 'ml' },
    { nom: 'Purée de coco', unite: 'g' },
    { nom: 'Graisse végétale', unite: 'g' },
    // Pâtes d'oléagineux
    { nom: 'Smen', unite: 'g' },
    { nom: 'Tahini', unite: 'g' },
    { nom: 'Purée de sésame', unite: 'g' },
    { nom: 'Beurre de cacahuète', unite: 'g' },
    { nom: 'Purée de cacahuète', unite: 'g' },
    { nom: 'Purée d\'amande', unite: 'g' },
    { nom: 'Purée d\'amande blanche', unite: 'g' },
    { nom: 'Purée d\'amande complète', unite: 'g' },
    { nom: 'Purée de noisette', unite: 'g' },
    { nom: 'Purée de noix de cajou', unite: 'g' },
    { nom: 'Purée de pistache', unite: 'g' },
    { nom: 'Purée de noix', unite: 'g' },
    // Farines — 'Farine de blé' existe déjà → ignorée
    { nom: 'Farine T45', unite: 'g' },
    { nom: 'Farine T55', unite: 'g' },
    { nom: 'Farine T65', unite: 'g' },
    { nom: 'Farine T80', unite: 'g' },
    { nom: 'Farine T110', unite: 'g' },
    { nom: 'Farine T150', unite: 'g' },
    { nom: 'Farine de gruau', unite: 'g' },
    { nom: 'Farine de riz', unite: 'g' },
    { nom: 'Farine de riz gluant', unite: 'g' },
    { nom: 'Farine de maïs', unite: 'g' },
    { nom: 'Farine de pois chiche', unite: 'g' },
    { nom: 'Farine de sarrasin', unite: 'g' },
    { nom: 'Farine d\'épeautre', unite: 'g' },
    { nom: 'Farine de petit épeautre', unite: 'g' },
    { nom: 'Farine de seigle', unite: 'g' },
    { nom: 'Farine d\'orge', unite: 'g' },
    { nom: 'Farine d\'avoine', unite: 'g' },
    { nom: 'Farine de millet', unite: 'g' },
    { nom: 'Farine de quinoa', unite: 'g' },
    { nom: 'Farine de châtaigne', unite: 'g' },
    { nom: 'Farine de coco', unite: 'g' },
    { nom: 'Farine d\'amande', unite: 'g' },
    { nom: 'Farine de noisette', unite: 'g' },
    { nom: 'Farine de lupin', unite: 'g' },
    { nom: 'Farine de soja', unite: 'g' },
    { nom: 'Farine de manioc', unite: 'g' },
    { nom: 'Farine de tapioca', unite: 'g' },
    { nom: 'Farine de teff', unite: 'g' },
    { nom: 'Farine de sorgho', unite: 'g' },
    { nom: 'Farine de pomme de terre', unite: 'g' },
    // Féculents
    { nom: 'Fécule de maïs', unite: 'g' },
    { nom: 'Fécule de pomme de terre', unite: 'g' },
    { nom: 'Fécule de tapioca', unite: 'g' },
    { nom: 'Arrow-root', unite: 'g' },
    // Semoules & flocons
    { nom: 'Semoule fine', unite: 'g' },
    { nom: 'Semoule moyenne', unite: 'g' },
    { nom: 'Semoule grosse', unite: 'g' },
    { nom: 'Semoule de blé dur', unite: 'g' },
    { nom: 'Polenta', unite: 'g' },
    { nom: 'Gruau d\'avoine', unite: 'g' },
    { nom: 'Flocons d\'avoine', unite: 'g' },
    { nom: 'Flocons de seigle', unite: 'g' },
    { nom: 'Flocons d\'épeautre', unite: 'g' },
    { nom: 'Flocons d\'orge', unite: 'g' },
    { nom: 'Son d\'avoine', unite: 'g' },
    { nom: 'Germe de blé', unite: 'g' },
    // Céréales brutes
    { nom: 'Blé', unite: 'g' },
    { nom: 'Blé concassé', unite: 'g' },
    { nom: 'Boulgour', unite: 'g' },
    { nom: 'Épeautre', unite: 'g' },
    { nom: 'Petit épeautre', unite: 'g' },
    { nom: 'Orge perlé', unite: 'g' },
    { nom: 'Orge mondé', unite: 'g' },
    { nom: 'Avoine', unite: 'g' },
    { nom: 'Millet', unite: 'g' },
    { nom: 'Quinoa blanc', unite: 'g' },
    { nom: 'Quinoa rouge', unite: 'g' },
    { nom: 'Quinoa noir', unite: 'g' },
    { nom: 'Amarante', unite: 'g' },
    { nom: 'Sorgho', unite: 'g' },
    { nom: 'Teff', unite: 'g' },
    { nom: 'Sarrasin', unite: 'g' },
    { nom: 'Graines de sarrasin', unite: 'g' },
    { nom: 'Maïs à pop-corn', unite: 'g' },
    { nom: 'Maïs concassé', unite: 'g' },
    { nom: 'Couscous perlé', unite: 'g' },
    { nom: 'Freekeh', unite: 'g' },
    { nom: 'Épeautre concassé', unite: 'g' },
    // Riz — 'Riz basmati' existe déjà → ignoré
    { nom: 'Riz blanc', unite: 'g' },
    { nom: 'Riz long grain', unite: 'g' },
    { nom: 'Riz rond', unite: 'g' },
    { nom: 'Riz jasmin', unite: 'g' },
    { nom: 'Riz thaï', unite: 'g' },
    { nom: 'Riz parfumé', unite: 'g' },
    { nom: 'Riz complet', unite: 'g' },
    { nom: 'Riz semi-complet', unite: 'g' },
    { nom: 'Riz rouge', unite: 'g' },
    { nom: 'Riz noir', unite: 'g' },
    { nom: 'Riz sauvage', unite: 'g' },
    { nom: 'Riz à sushi', unite: 'g' },
    { nom: 'Riz gluant', unite: 'g' },
    { nom: 'Riz arborio', unite: 'g' },
    { nom: 'Riz carnaroli', unite: 'g' },
    { nom: 'Riz vialone nano', unite: 'g' },
    { nom: 'Riz bomba', unite: 'g' },
    { nom: 'Riz pour paella', unite: 'g' },
    { nom: 'Vermicelles de riz', unite: 'g' },
    { nom: 'Nouilles de riz', unite: 'g' },
    { nom: 'Nouilles de riz larges', unite: 'g' },
    { nom: 'Galettes de riz', unite: 'pièce(s)' },
    { nom: 'Feuilles de riz', unite: 'pièce(s)' },
    // Pâtes — 'Spaghetti' existe déjà → ignoré
    { nom: 'Tagliatelle', unite: 'g' },
    { nom: 'Linguine', unite: 'g' },
    { nom: 'Bucatini', unite: 'g' },
    { nom: 'Fusilli', unite: 'g' },
    { nom: 'Penne', unite: 'g' },
    { nom: 'Rigatoni', unite: 'g' },
    { nom: 'Farfalle', unite: 'g' },
    { nom: 'Orecchiette', unite: 'g' },
    { nom: 'Conchiglie', unite: 'g' },
    { nom: 'Macaroni', unite: 'g' },
    { nom: 'Gnocchi', unite: 'g' },
    { nom: 'Lasagnes', unite: 'g' },
    { nom: 'Cannelloni', unite: 'g' },
    { nom: 'Pappardelle', unite: 'g' },
    { nom: 'Fettuccine', unite: 'g' },
    { nom: 'Capellini', unite: 'g' },
    { nom: 'Vermicelles', unite: 'g' },
    { nom: 'Coquillettes', unite: 'g' },
    { nom: 'Crozets', unite: 'g' },
    { nom: 'Orzo', unite: 'g' },
    { nom: 'Nouilles aux œufs', unite: 'g' },
    { nom: 'Nouilles de blé', unite: 'g' },
    { nom: 'Nouilles instantanées', unite: 'g' },
    { nom: 'Nouilles de haricot mungo', unite: 'g' },
    { nom: 'Vermicelles de haricot mungo', unite: 'g' },
    { nom: 'Nouilles de patate douce', unite: 'g' },
    { nom: 'Gnocchis à poêler', unite: 'g' },
    // Féculents & tubercules transformés
    { nom: 'Purée de pommes de terre en flocons', unite: 'g' },
    { nom: 'Igname', unite: 'kg' },
    { nom: 'Manioc', unite: 'kg' },
    { nom: 'Tapioca', unite: 'g' },
    { nom: 'Perles du Japon', unite: 'g' },
    { nom: 'Sagou', unite: 'g' },
    // Produits maghrébins salés
    { nom: 'Harissa', unite: 'g' },
    { nom: 'Eau de fleur d\'oranger', unite: 'ml' },
    { nom: 'Eau de rose', unite: 'ml' },
    { nom: 'Mélasse de grenade', unite: 'ml' },
    { nom: 'Sirop de datte', unite: 'ml' },
    { nom: 'Houmous', unite: 'g' },
    { nom: 'Falafel', unite: 'g' },
    { nom: 'Citron confit', unite: 'pièce(s)' },
    { nom: 'Citron noir séché', unite: 'g' },
    { nom: 'Loumi', unite: 'g' },
    { nom: 'Pâte de dattes', unite: 'g' },
    { nom: 'Feuilles de brick', unite: 'pièce(s)' },
    { nom: 'Malsouka', unite: 'pièce(s)' },
    { nom: 'Mélasse de caroube', unite: 'ml' },
    // Sauces & condiments
    // 'Sauce tomate' et 'Concentré de tomates' existent déjà → ignorés
    { nom: 'Moutarde', unite: 'g' },
    { nom: 'Moutarde de Dijon', unite: 'g' },
    { nom: 'Moutarde à l\'ancienne', unite: 'g' },
    { nom: 'Ketchup', unite: 'ml' },
    { nom: 'Mayonnaise', unite: 'g' },
    { nom: 'Sauce barbecue', unite: 'ml' },
    { nom: 'Sauce burger', unite: 'ml' },
    { nom: 'Sauce samouraï', unite: 'ml' },
    { nom: 'Sauce algérienne', unite: 'ml' },
    { nom: 'Sauce andalouse', unite: 'ml' },
    { nom: 'Sauce blanche', unite: 'ml' },
    { nom: 'Sauce fromagère', unite: 'ml' },
    { nom: 'Sauce cocktail', unite: 'ml' },
    { nom: 'Sauce tartare', unite: 'ml' },
    { nom: 'Sauce burger cheese', unite: 'ml' },
    { nom: 'Sauce Worcestershire', unite: 'ml' },
    { nom: 'Vinaigrette', unite: 'ml' },
    { nom: 'Vinaigrette balsamique', unite: 'ml' },
    { nom: 'Vinaigrette citron', unite: 'ml' },
    { nom: 'Vinaigrette moutarde', unite: 'ml' },
    { nom: 'Vinaigrette miel', unite: 'ml' },
    { nom: 'Sauce béchamel', unite: 'ml' },
    { nom: 'Sauce hollandaise', unite: 'ml' },
    { nom: 'Sauce beurre blanc', unite: 'ml' },
    { nom: 'Sauce au poivre', unite: 'ml' },
    { nom: 'Sauce aux champignons', unite: 'ml' },
    { nom: 'Sauce vin blanc', unite: 'ml' },
    { nom: 'Coulis de tomate', unite: 'ml' },
    { nom: 'Double concentré de tomate', unite: 'g' },
    { nom: 'Sauce pesto', unite: 'ml' },
    { nom: 'Pesto vert', unite: 'g' },
    { nom: 'Pesto rouge', unite: 'g' },
    { nom: 'Sauce carbonara', unite: 'ml' },
    { nom: 'Fond de veau', unite: 'ml' },
    { nom: 'Fond de volaille', unite: 'ml' },
    { nom: 'Fond de bœuf', unite: 'ml' },
    { nom: 'Bouillon de légumes', unite: 'ml' },
    { nom: 'Bouillon de volaille', unite: 'ml' },
    { nom: 'Bouillon de bœuf', unite: 'ml' },
    { nom: 'Bouillon de poisson', unite: 'ml' },
    { nom: 'Bouillon cube', unite: 'pièce(s)' },
    { nom: 'Fumet de poisson', unite: 'ml' },
    { nom: 'Glace de viande', unite: 'g' },
    { nom: 'Jus de viande', unite: 'ml' },
    { nom: 'Jus de cuisson', unite: 'ml' },
    { nom: 'Réduction', unite: 'ml' },
    { nom: 'Farine complète', unite: 'g' },
    { nom: 'Pâte feuilletée', unite: 'g' },
    { nom: 'Pâte brisée', unite: 'g' },
    { nom: 'Pâte sablée', unite: 'g' },
    { nom: 'Pâte à pizza', unite: 'g' },
    { nom: 'Pâte à pain', unite: 'g' },
    { nom: 'Salsa', unite: 'g' },
    { nom: 'Salsa roja', unite: 'g' },
    { nom: 'Salsa verde', unite: 'g' },
    { nom: 'Guacamole', unite: 'g' },
    { nom: 'Pico de gallo', unite: 'g' },
    { nom: 'Chimichurri', unite: 'g' },
    { nom: 'Mole', unite: 'g' },
    { nom: 'Romesco', unite: 'g' },
    { nom: 'Tapenade noire', unite: 'g' },
    { nom: 'Tapenade verte', unite: 'g' },
    { nom: 'Caviar d\'aubergine', unite: 'g' },
    { nom: 'Tzatziki', unite: 'g' },
    { nom: 'Aïoli', unite: 'g' },
    { nom: 'Rouille', unite: 'g' },
    { nom: 'Pistou', unite: 'g' },
    { nom: 'Réduction balsamique', unite: 'ml' },
    { nom: 'Crème de balsamique', unite: 'ml' },
    { nom: 'Velour de balsamique', unite: 'ml' },
  ],

  // ─── Produits Laitiers ───────────────────────────────────────────────────────
  // 'Beurre doux' et 'Beurre salé' ajoutés par migration → présents mais on les
  // inclut ici pour un seed cohérent (la migration les skippe s'ils existent déjà)
  'Produits Laitiers': [
    { nom: 'Beurre doux', unite: 'g' },
    { nom: 'Beurre demi-sel', unite: 'g' },
    { nom: 'Beurre salé', unite: 'g' },
    { nom: 'Beurre clarifié', unite: 'g' },
    { nom: 'Ghee', unite: 'g' },
  ],

  // ─── Fromages ───────────────────────────────────────────────────────────────
  Fromages: [
    { nom: 'Fromage akkawi', unite: 'g' },
    { nom: 'Fromage nabulsi', unite: 'g' },
  ],

  // ─── Épicerie sucrée ─────────────────────────────────────────────────────────
  // 'Sucre glace', 'Miel', 'Chocolat noir', 'Levure chimique' existent déjà → ignorés
  'Épicerie sucrée': [
    // Sucres
    { nom: 'Sucre blanc', unite: 'g' },
    { nom: 'Sucre blond', unite: 'g' },
    { nom: 'Sucre roux', unite: 'g' },
    { nom: 'Cassonade', unite: 'g' },
    { nom: 'Vergeoise blonde', unite: 'g' },
    { nom: 'Vergeoise brune', unite: 'g' },
    { nom: 'Sucre muscovado', unite: 'g' },
    { nom: 'Sucre de canne', unite: 'g' },
    { nom: 'Sucre perlé', unite: 'g' },
    { nom: 'Sucre en morceaux', unite: 'g' },
    { nom: 'Sucre inverti', unite: 'g' },
    { nom: 'Glucose', unite: 'g' },
    { nom: 'Sirop de glucose', unite: 'ml' },
    { nom: 'Sirop de maïs', unite: 'ml' },
    { nom: 'Mélasse', unite: 'ml' },
    { nom: 'Sirop d\'érable', unite: 'ml' },
    { nom: 'Sirop d\'agave', unite: 'ml' },
    { nom: 'Sucre de palme', unite: 'g' },
    { nom: 'Sucre de coco', unite: 'g' },
    { nom: 'Tréhalose', unite: 'g' },
    // Levures & agents levants
    { nom: 'Bicarbonate de soude', unite: 'g' },
    { nom: 'Levure boulangère fraîche', unite: 'g' },
    { nom: 'Levure boulangère sèche', unite: 'g' },
    { nom: 'Levain', unite: 'g' },
    { nom: 'Améliorant de boulangerie', unite: 'g' },
    // Chocolats — 'Chocolat noir' existe déjà → ignoré
    { nom: 'Chocolat au lait', unite: 'g' },
    { nom: 'Chocolat blanc', unite: 'g' },
    { nom: 'Chocolat de couverture noir', unite: 'g' },
    { nom: 'Chocolat de couverture au lait', unite: 'g' },
    { nom: 'Chocolat de couverture blanc', unite: 'g' },
    { nom: 'Cacao en poudre', unite: 'g' },
    { nom: 'Cacao non sucré', unite: 'g' },
    { nom: 'Beurre de cacao', unite: 'g' },
    { nom: 'Pépites de chocolat', unite: 'g' },
    { nom: 'Grué de cacao', unite: 'g' },
    // Vanille & arômes
    { nom: 'Gousse de vanille', unite: 'pièce(s)' },
    { nom: 'Poudre de vanille', unite: 'g' },
    { nom: 'Extrait de vanille', unite: 'ml' },
    { nom: 'Arôme vanille', unite: 'ml' },
    { nom: 'Extrait d\'amande amère', unite: 'ml' },
    { nom: 'Arôme fleur d\'oranger', unite: 'ml' },
    { nom: 'Arôme citron', unite: 'ml' },
    { nom: 'Arôme rhum', unite: 'ml' },
    // Confiserie & praliné
    { nom: 'Pralin', unite: 'g' },
    { nom: 'Praliné', unite: 'g' },
    { nom: 'Pâte de praliné', unite: 'g' },
    { nom: 'Praliné noisette', unite: 'g' },
    { nom: 'Praliné amande', unite: 'g' },
    { nom: 'Nougatine', unite: 'g' },
    { nom: 'Massepain', unite: 'g' },
    { nom: 'Pâte d\'amande', unite: 'g' },
    { nom: 'Pâte de pistache', unite: 'g' },
    { nom: 'Crème de marrons', unite: 'g' },
    { nom: 'Marrons glacés', unite: 'g' },
    { nom: 'Gianduja', unite: 'g' },
    { nom: 'Halva', unite: 'g' },
    { nom: 'Loukoum', unite: 'g' },
    // Produits laitiers sucrés
    { nom: 'Lait concentré sucré', unite: 'g' },
    { nom: 'Lait concentré non sucré', unite: 'g' },
    { nom: 'Lait en poudre', unite: 'g' },
    // Gélifiants & stabilisants
    { nom: 'Gélatine', unite: 'g' },
    { nom: 'Gélatine en feuilles', unite: 'g' },
    { nom: 'Gélatine en poudre', unite: 'g' },
    { nom: 'Agar-agar', unite: 'g' },
    { nom: 'Pectine', unite: 'g' },
    { nom: 'Pectine NH', unite: 'g' },
    { nom: 'Pectine jaune', unite: 'g' },
    { nom: 'Pectine de pomme', unite: 'g' },
    { nom: 'Gomme xanthane', unite: 'g' },
    { nom: 'Gomme guar', unite: 'g' },
    { nom: 'Gomme arabique', unite: 'g' },
    { nom: 'Gélifiant végétal', unite: 'g' },
    { nom: 'Isomalt', unite: 'g' },
    { nom: 'Crème de tartre', unite: 'g' },
    { nom: 'Acide citrique', unite: 'g' },
    { nom: 'Acide ascorbique', unite: 'g' },
    // Pâtisserie avancée
    { nom: 'Fondant pâtissier', unite: 'g' },
    { nom: 'Nappage neutre', unite: 'g' },
    { nom: 'Blanc d\'œuf en poudre', unite: 'g' },
    { nom: 'Albumine', unite: 'g' },
    { nom: 'Meringue en poudre', unite: 'g' },
    { nom: 'Préparation pour crème pâtissière', unite: 'g' },
    { nom: 'Stabilisateur pour chantilly', unite: 'g' },
    { nom: 'Fixateur pour chantilly', unite: 'g' },
    { nom: 'Pâte à sucre', unite: 'g' },
    { nom: 'Pâte à fleurs', unite: 'g' },
    { nom: 'Pâte à gum paste', unite: 'g' },
    { nom: 'Glaçage royal', unite: 'g' },
    // Décoration
    { nom: 'Perles de sucre', unite: 'g' },
    { nom: 'Vermicelles en chocolat', unite: 'g' },
    { nom: 'Fruits confits', unite: 'g' },
    { nom: 'Écorces d\'orange confites', unite: 'g' },
    { nom: 'Écorces de citron confites', unite: 'g' },
    { nom: 'Cerises confites', unite: 'g' },
    { nom: 'Bigarreaux confits', unite: 'g' },
    { nom: 'Colorant alimentaire liquide', unite: 'flacon(s)' },
    { nom: 'Colorant alimentaire en poudre', unite: 'g' },
    { nom: 'Colorant alimentaire gel', unite: 'pot(s)' },
    { nom: 'Sucre décor', unite: 'g' },
    { nom: 'Paillettes alimentaires', unite: 'g' },
    { nom: 'Feuille d\'or alimentaire', unite: 'pièce(s)' },
    { nom: 'Sprinkles', unite: 'g' },
    { nom: 'Brillant alimentaire', unite: 'g' },
    // Fruits secs
    { nom: 'Abricots secs', unite: 'g' },
    { nom: 'Figues sèches', unite: 'g' },
    { nom: 'Pruneaux', unite: 'g' },
    { nom: 'Raisins secs', unite: 'g' },
    { nom: 'Cranberries séchées', unite: 'g' },
    // Oléagineux transformés
    { nom: 'Amandes effilées', unite: 'g' },
    { nom: 'Amandes en poudre', unite: 'g' },
    { nom: 'Noisettes en poudre', unite: 'g' },
    { nom: 'Pistaches concassées', unite: 'g' },
    { nom: 'Noix de coco râpée', unite: 'g' },
    { nom: 'Éclats de fèves de cacao', unite: 'g' },
    // Purées de fruits
    { nom: 'Purée de framboise', unite: 'g' },
    { nom: 'Purée de mangue', unite: 'g' },
    { nom: 'Purée de passion', unite: 'g' },
    { nom: 'Purée de fraise', unite: 'g' },
    { nom: 'Purée de citron', unite: 'g' },
  ],

  // ─── Asiatique ───────────────────────────────────────────────────────────────
  // Doublons avec Épicerie salée exclus : huile de sésame, vinaigre de riz,
  // lait de coco, farine de riz, riz à sushi, nouilles de riz, etc.
  // Doublons avec Épicerie sucrée exclus : agar-agar, sucre de palme/coco.
  Asiatique: [
    // Sauces & assaisonnements
    { nom: 'Sauce soja', unite: 'ml' },
    { nom: 'Sauce soja claire', unite: 'ml' },
    { nom: 'Sauce soja foncée', unite: 'ml' },
    { nom: 'Sauce soja sucrée', unite: 'ml' },
    { nom: 'Tamari', unite: 'ml' },
    { nom: 'Shoyu', unite: 'ml' },
    { nom: 'Miso blanc', unite: 'g' },
    { nom: 'Miso rouge', unite: 'g' },
    { nom: 'Miso brun', unite: 'g' },
    { nom: 'Miso', unite: 'g' },
    { nom: 'Mirin', unite: 'ml' },
    { nom: 'Saké de cuisine', unite: 'ml' },
    { nom: 'Sauce huître', unite: 'ml' },
    { nom: 'Sauce poisson', unite: 'ml' },
    { nom: 'Nuoc-mâm', unite: 'ml' },
    { nom: 'Sauce teriyaki', unite: 'ml' },
    { nom: 'Sauce yakitori', unite: 'ml' },
    { nom: 'Sauce ponzu', unite: 'ml' },
    { nom: 'Sauce tonkatsu', unite: 'ml' },
    { nom: 'Sauce okonomiyaki', unite: 'ml' },
    { nom: 'Sauce satay', unite: 'ml' },
    { nom: 'Sauce chili douce', unite: 'ml' },
    { nom: 'Sauce hoisin', unite: 'ml' },
    { nom: 'Sauce aux haricots noirs', unite: 'ml' },
    { nom: 'Sauce XO', unite: 'g' },
    { nom: 'Doubanjiang', unite: 'g' },
    { nom: 'Gochujang', unite: 'g' },
    { nom: 'Ssamjang', unite: 'g' },
    { nom: 'Pâte de curry rouge', unite: 'g' },
    { nom: 'Pâte de curry vert', unite: 'g' },
    { nom: 'Pâte de curry jaune', unite: 'g' },
    { nom: 'Pâte de tamarin', unite: 'g' },
    { nom: 'Pâte de crevettes', unite: 'g' },
    { nom: 'Sambal oelek', unite: 'g' },
    { nom: 'Sambal', unite: 'g' },
    // Tofu & protéines végétales
    { nom: 'Tofu ferme', unite: 'g' },
    { nom: 'Tofu extra ferme', unite: 'g' },
    { nom: 'Tofu soyeux', unite: 'g' },
    { nom: 'Tofu fumé', unite: 'g' },
    { nom: 'Tofu frit', unite: 'g' },
    { nom: 'Peau de tofu', unite: 'g' },
    { nom: 'Yuba', unite: 'g' },
    { nom: 'Tempeh', unite: 'g' },
    { nom: 'Natto', unite: 'g' },
    { nom: 'Edamame', unite: 'g' },
    { nom: 'Protéines de soja texturées', unite: 'g' },
    { nom: 'Lait de soja', unite: 'ml' },
    { nom: 'Crème de soja', unite: 'ml' },
    // Nouilles asiatiques
    { nom: 'Ramen', unite: 'g' },
    { nom: 'Udon', unite: 'g' },
    { nom: 'Soba', unite: 'g' },
    { nom: 'Somen', unite: 'g' },
    { nom: 'Nouilles shirataki', unite: 'g' },
    { nom: 'Yakisoba', unite: 'g' },
    { nom: 'Wonton', unite: 'g' },
    { nom: 'Raviolis chinois', unite: 'g' },
    { nom: 'Gyoza', unite: 'g' },
    // Panure
    { nom: 'Panko', unite: 'g' },
    // Légumes & champignons asiatiques
    { nom: 'Champignon shiitaké', unite: 'g' },
    { nom: 'Champignon enoki', unite: 'g' },
    { nom: 'Champignon eryngii', unite: 'g' },
    { nom: 'Champignon noir séché', unite: 'g' },
    { nom: 'Oreille de Judas', unite: 'g' },
    { nom: 'Pousse de bambou', unite: 'g' },
    { nom: 'Châtaigne d\'eau', unite: 'g' },
    { nom: 'Racine de lotus', unite: 'g' },
    { nom: 'Haricots mungo', unite: 'g' },
    { nom: 'Pousses de soja', unite: 'g' },
    { nom: 'Jeunes épis de maïs', unite: 'g' },
    { nom: 'Fécule de patate douce', unite: 'g' },
    // Algues
    { nom: 'Algue nori', unite: 'g' },
    { nom: 'Algue wakamé', unite: 'g' },
    { nom: 'Algue kombu', unite: 'g' },
    { nom: 'Algue hijiki', unite: 'g' },
    { nom: 'Algue dulse', unite: 'g' },
    // Bouillons & condiments japonais
    { nom: 'Furikake', unite: 'g' },
    { nom: 'Bonite séchée', unite: 'g' },
    { nom: 'Katsuobushi', unite: 'g' },
    { nom: 'Dashi', unite: 'g' },
    { nom: 'Bouillon dashi', unite: 'ml' },
    { nom: 'Bouillon miso', unite: 'ml' },
    { nom: 'Bouillon asiatique', unite: 'ml' },
    { nom: 'Wasabi', unite: 'g' },
    { nom: 'Raifort japonais', unite: 'g' },
    { nom: 'Gingembre mariné', unite: 'g' },
    // Fermentés & marinades
    { nom: 'Tsukemono', unite: 'g' },
    { nom: 'Kimchi', unite: 'g' },
    { nom: 'Radis mariné coréen', unite: 'g' },
    // Garnitures frites
    { nom: 'Ail frit', unite: 'g' },
    { nom: 'Échalote frite', unite: 'g' },
    { nom: 'Oignons frits', unite: 'g' },
    // Graines de sésame
    { nom: 'Graines de sésame blanches', unite: 'g' },
    { nom: 'Graines de sésame noires', unite: 'g' },
    { nom: 'Graines de sésame dorées', unite: 'g' },
    // Conserves & sucreries asiatiques
    { nom: 'Litchis en conserve', unite: 'boîte(s)' },
    { nom: 'Longane en conserve', unite: 'boîte(s)' },
    { nom: 'Gelée de coco', unite: 'g' },
    { nom: 'Perles de tapioca', unite: 'g' },
    { nom: 'Boba', unite: 'g' },
    { nom: 'Gelée d\'herbe', unite: 'g' },
    // Poudres & arômes asiatiques
    { nom: 'Matcha', unite: 'g' },
    { nom: 'Thé jasmin', unite: 'g' },
    { nom: 'Poudre de taro', unite: 'g' },
    { nom: 'Ube', unite: 'g' },
    { nom: 'Pandan', unite: 'g' },
    { nom: 'Extrait de pandan', unite: 'ml' },
    { nom: 'Feuille de pandan', unite: 'pièce(s)' },
  ],
};

export async function seedProduits(): Promise<void> {
  // Récupérer les catégories par nom pour obtenir leurs IDs dynamiques
  const categories = await db.categoriesProduits.toArray();
  const catMap = new Map(categories.map((c: { nom: string; id: string }) => [c.nom, c.id]));

  const produits: Produit[] = [];

  for (const [nomCategorie, items] of Object.entries(PRODUITS_PAR_CATEGORIE)) {
    const categorieId = catMap.get(nomCategorie);
    if (!categorieId) {
      console.warn(`[seedProduits] Catégorie introuvable : ${nomCategorie}`);
      continue;
    }

    for (const item of items) {
      produits.push(
        newEntity<Produit>({
          nom: item.nom,
          nomNormalise: normaliserNom(item.nom),
          type: 'consommable',
          categorie: categorieId,
          categorieIds: [categorieId],
          unite: item.unite,
          marque: item.marque,
          frequenceAchat: 0,
          archive: false,
        })
      );
    }
  }

  await db.produits.bulkAdd(produits);
  console.log(`[FamilyOS] ${produits.length} produits initialisés.`);
}
