import './styles/index.css'
import { initTheme } from './shared/hooks/useTheme'
import React from 'react'

initTheme()
import ReactDOM from 'react-dom/client'
import App from './App'

// Auto-récupération : après un déploiement, le SW peut servir un index.html
// périmé qui référence des chunks JS supprimés du serveur (404 sur import()).
// On détecte cet échec et on force un rechargement unique pour récupérer
// la nouvelle version, plutôt que de laisser l'app bloquée sur un écran blanc.
function estErreurChunkPerime(message: string): boolean {
  return /error loading dynamically imported module|failed to fetch dynamically imported module|importing a module script failed/i.test(message)
}

async function recupererApresChunkPerime() {
  const cle = 'family-os:chunk-reload'
  if (sessionStorage.getItem(cle)) return // déjà tenté dans cette session, éviter une boucle
  sessionStorage.setItem(cle, '1')

  // Le SW (cache-first) peut continuer à servir l'ancien index.html après un
  // simple reload : on désinscrit le SW et on vide ses caches avant de recharger,
  // pour forcer la récupération de la nouvelle version depuis le réseau.
  try {
    const regs = await navigator.serviceWorker?.getRegistrations() ?? []
    await Promise.all(regs.map(r => r.unregister()))
    const cles = await caches?.keys() ?? []
    await Promise.all(cles.map(c => caches.delete(c)))
  } catch {
    // best-effort — on recharge dans tous les cas
  } finally {
    window.location.reload()
  }
}

window.addEventListener('error', e => {
  if (e.message && estErreurChunkPerime(e.message)) recupererApresChunkPerime()
})
window.addEventListener('unhandledrejection', e => {
  const message = e.reason?.message ?? String(e.reason ?? '')
  if (estErreurChunkPerime(message)) recupererApresChunkPerime()
})

// Register Service Worker (generated by vite-plugin-pwa)
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker
      .register('/family-os/sw.js', { scope: '/family-os/' })
      .catch((err) => {
        console.warn('[SW] Registration failed:', err)
      })
  })
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
