import './styles/index.css'
import { initTheme } from './shared/hooks/useTheme'
import React from 'react'

initTheme()
import ReactDOM from 'react-dom/client'
import App from './App'

// Register Service Worker (generated by vite-plugin-pwa)
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker
      .register('/family-os/sw.js', { scope: '/family-os/' })
      .catch((err) => {
        console.warn('[SW] Registration failed:', err)
      })
  })
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
